language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
cache: bundler
before_script:
  - cp test/app/config/database.travis.yml test/app/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
  - RAILS_ENV=test bundle exec rake test
notifications:
  email: gonzalo@robaina.me
addons:
  code_climate:
    repo_token: d2b776330f7514d7a959cfaf6982bee026b317666ab93adddb4fcaabce96eb5e
